# build settings
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
google_analytics: G-NHDCW35LLY


title: Short Stories About Asha Galaxy
description: Get ready for the ultimate sci-fi gaming experience as you step into the world of the Asha Empire.
